export const ADD_ORIGIN_STATION = "ADD_ORIGIN_STATION";
export const ADD_DEP_STATION = "ADD_DEP_STATION";
export const ADD_DATE_STATION = "ADD_DATE_STATION";
export const CLEAR_SEARCH = "CLEAR_SEARCH";
export const ADD_SEARCH_ROUTE = "ADD_SEARCH_ROUTE";
