export const ADD_ORIGIN_STATION = "ADD_ORIGIN_STATION";
export const ADD_DEP_STATION = "ADD_DEP_STATION";
export const ADD_DATE_STATION = "ADD_DATE_STATION";
export const CLEAR_SEARCH = "CLEAR_SEARCH";
export const ADD_SEARCH_ROUTE_FULFILLED = "ADD_SEARCH_ROUTE_FULFILLED";
export const ADD_SEARCH_ROUTE_PENDING = "ADD_SEARCH_ROUTE_PENDING";

export const CHANGE_SELECTED_ROUTE = "CHANGE_SELECTED_ROUTE";
export const REMOVE_SELECTED_ROUTE_ON = "REMOVE_SELECTED_ROUTE_ON";
export const REMOVE_SELECTED_ROUTE = "REMOVE_SELECTED_ROUTE";

export const SIDEBAR_TOGGLE = "SIDEBAR_TOGGLE";

